services:
  frontend:
    container_name: toey-sawatdee
    image: ghcr.io/https://github.com/ttser123/toey-sawatdee.git/toey-sawatdee:latest
    ports:
      - "80:3000"
    env_file:
      - .env.local
    restart: unless-stopped
